# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the Node.js version you use

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test -- --coverage  # Adjust this command if necessary for your test script

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage  # Adjust this path to match where your coverage report is generated

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/coverage-final.json  # Adjust if necessary for your coverage output file
